language: android
jdk:
 - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
 - chmod +x gradlew

script:
 - ./gradlew test build
